name: Publish to PyPI
on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write # required to push git tags
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install UV
              run: curl -LsSf https://astral.sh/uv/install.sh | sh

            - name: Build and Publish
              env:
                  UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
              run: |
                uv build
                uv publish

            - name: Tag release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  VERSION=$(uv version --short)
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  gh release create "v$VERSION" --notes-file ./CHANGELOG.md
