name: Publish to TestPyPI
on:
    push:
        branches:
            - develop
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install UV
              run: curl -LsSf https://astral.sh/uv/install.sh | sh

            - name: Build and Publish to TestPyPI
              env:
                  UV_PUBLISH_USERNAME: __token__
                  UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
              run: |
                uv build
                uv publish --index testpypi
